// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwlujdjeyexrkphhgupl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bHVqZGpleWV4cmtwaGhndXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTM5OTEsImV4cCI6MjA3NTMyOTk5MX0.Pkx4kLnodWEwP6yzseTUhNZ6M2cwe0FJ1npxW_E25EM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});