// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umermlglgpqnpvtuxxxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtZXJtbGdsZ3BxbnB2dHV4eHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDEwMjMsImV4cCI6MjA3MDkxNzAyM30.iQp5URZUNydsWpdqV6dC0-mQqCKdzMiLKI8pOi7KpeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});