// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgoeoweihremlqxsifup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnb2Vvd2VpaHJlbWxxeHNpZnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNzI0MDcsImV4cCI6MjA4ODY0ODQwN30.-epDgw48xKFZvhPCuW-z2GL0wGEKZa2n65fbdyF2DXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});